version: '3'
services:
    mysql:
        image: 'mysql:5.7'
        restart: "unless-stopped"
        env_file:
            - ".env"
        ports:
            - "3306:3306"
        volumes:
            - "./database/init:/docker-entrypoint-initdb.d"
            - "./database/data:/var/lib/mysql/"
    
    php:
        build: . 
        restart: "unless-stopped"
        depends_on:
            - mysql
        volumes:
        #- "/var/www/html"
             - "./api:/var/www/html"
        #- "./var/www/html"
        ports:
              - "9090:80"


    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        restart: "unless-stopped"
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
        ports:
              - "8080:80"